"""Public inventory of semantic-index package surfaces."""

SEMANTIC_INDEX_SURFACES = (
    "SemanticIndexBackend",
    "SemanticIndexDeleteRequest",
    "SemanticIndexHealth",
    "SemanticIndexRebuildPlan",
    "SemanticIndexVector",
    "SemanticIndexVectorMatch",
    "SemanticIndexVectorQuery",
    "SemanticIndexWriteResult",
    "SemanticIndexDocument",
    "SemanticIndexDeleteResult",
    "SemanticIndexMetadataRebuildPlan",
    "SemanticIndexRepository",
    "SemanticIndexService",
    "FUSION_WEIGHTS",
    "HybridSemanticSearcher",
    "SemanticSearchMatch",
    "SemanticSearchQuery",
    "SemanticSearchRepository",
    "SQLiteVecSemanticIndex",
    "SQLITE_VEC_PACKAGE",
    "SQLITE_VEC_VERSION",
    "SQLiteVecLoadState",
    "load_sqlite_vec_extension",
    "semantic_content_hash",
    "semantic_index_entry_id",
    "sqlite_vec_dependency_state",
    "sqlite_vec_runtime_state",
)
