"""Public inventory of model package surfaces."""

MODEL_SURFACES = (
    "ModelAdapterDescriptor",
    "ModelRequest",
    "ModelUsage",
    "ModelTextResult",
    "ModelEmbeddingResult",
    "ModelAdapter",
    "CredentialSource",
    "ProviderTransportDefinition",
    "ProviderManifest",
    "ProviderCatalogRecord",
    "ProviderSetupGuide",
    "ProviderRuntimeResolution",
    "ProviderTransportRegistry",
    "ProviderManifestRegistry",
    "ProviderRuntimeResolver",
    "InMemoryModelAdapterRegistry",
    "InMemoryProviderTransportRegistry",
    "InMemoryProviderManifestRegistry",
    "AuthHeaderStrategy",
    "InMemoryAuthHeaderStrategyRegistry",
    "ProviderMetadataProbe",
    "ProviderMetadataProbeRegistry",
    "ProviderMetadataDiscoveryService",
    "ProviderStateEvaluator",
    "DiscoveredProviderModel",
    "DiscoveredProviderState",
    "EmbeddingBootstrapState",
    "SurfaceModelProviderCapability",
    "PromptEchoModelAdapter",
    "StaticTextModelAdapter",
    "PreviewModelProviderCapability",
)
