"""Reset storage repository implementation."""

from __future__ import annotations

from pathlib import Path

from . import repository_bootstrap_methods as _bootstrap_methods
from . import repository_canonical_methods as _canonical_methods
from . import repository_curiosity_methods as _curiosity_methods
from . import repository_provider_auth_methods as _provider_auth_methods
from . import repository_scope_methods as _scope_methods
from . import repository_system_methods as _system_methods
from .repository_support import StorageBootstrapState


class RuntimeStorageRepository:
    def __init__(self, database_path: str | Path) -> None:
        self.database_path = Path(database_path)


RuntimeStorageRepository.bootstrap = _bootstrap_methods.bootstrap
RuntimeStorageRepository.connection = _bootstrap_methods.connection
RuntimeStorageRepository.schema_version = _bootstrap_methods.schema_version

RuntimeStorageRepository.upsert_personal_model_runtime_state = _system_methods.upsert_personal_model_runtime_state
RuntimeStorageRepository.load_personal_model_runtime_state = _system_methods.load_personal_model_runtime_state
RuntimeStorageRepository.upsert_personal_model = _system_methods.upsert_personal_model
RuntimeStorageRepository.load_personal_model = _system_methods.load_personal_model
RuntimeStorageRepository.list_personal_models = _system_methods.list_personal_models
RuntimeStorageRepository.ensure_default_personal_model = _system_methods.ensure_default_personal_model
RuntimeStorageRepository.upsert_elephant_identity = _canonical_methods.upsert_elephant_identity
RuntimeStorageRepository.load_elephant_identity_for_profile = _canonical_methods.load_elephant_identity_for_profile
RuntimeStorageRepository.create_state = _system_methods.create_state
RuntimeStorageRepository.upsert_state = _system_methods.upsert_state
RuntimeStorageRepository.load_state = _system_methods.load_state
RuntimeStorageRepository.list_states = _system_methods.list_states
RuntimeStorageRepository.current_state = _system_methods.current_state
RuntimeStorageRepository.switch_state = _system_methods.switch_state
RuntimeStorageRepository.delete_state = _system_methods.delete_state
RuntimeStorageRepository.upsert_episode = _system_methods.upsert_episode
RuntimeStorageRepository.load_episode = _system_methods.load_episode
RuntimeStorageRepository.list_episodes = _system_methods.list_episodes
RuntimeStorageRepository.upsert_loop = _system_methods.upsert_loop
RuntimeStorageRepository.load_loop = _system_methods.load_loop
RuntimeStorageRepository.list_loops = _system_methods.list_loops
RuntimeStorageRepository.upsert_step = _system_methods.upsert_step
RuntimeStorageRepository.load_step = _system_methods.load_step
RuntimeStorageRepository.list_steps = _system_methods.list_steps
RuntimeStorageRepository.upsert_episode_state = _system_methods.upsert_episode_state
RuntimeStorageRepository.load_episode_state = _system_methods.load_episode_state
RuntimeStorageRepository.refresh_episode_state = _system_methods.refresh_episode_state
RuntimeStorageRepository.record_episode_resume = _system_methods.record_episode_resume
RuntimeStorageRepository.episode_lineage = _system_methods.episode_lineage
RuntimeStorageRepository.delete_episodes = _system_methods.delete_episodes
RuntimeStorageRepository.delete_orphaned_profiles = _system_methods.delete_orphaned_profiles
RuntimeStorageRepository.upsert_personal_model_growth = _system_methods.upsert_personal_model_growth
RuntimeStorageRepository.load_personal_model_growth = _system_methods.load_personal_model_growth
RuntimeStorageRepository.enqueue_learning_job = _system_methods.enqueue_learning_job
RuntimeStorageRepository.load_learning_job = _system_methods.load_learning_job
RuntimeStorageRepository.load_learning_job_for_episode = _system_methods.load_learning_job_for_episode
RuntimeStorageRepository.list_learning_jobs = _system_methods.list_learning_jobs
RuntimeStorageRepository.claim_learning_job = _system_methods.claim_learning_job
RuntimeStorageRepository.update_learning_job_progress = _system_methods.update_learning_job_progress
RuntimeStorageRepository.write_learning_job_result = _system_methods.write_learning_job_result
RuntimeStorageRepository.complete_learning_job = _system_methods.complete_learning_job
RuntimeStorageRepository.fail_learning_job = _system_methods.fail_learning_job
RuntimeStorageRepository.upsert_loop_checkpoint = _system_methods.upsert_loop_checkpoint
RuntimeStorageRepository.load_latest_open_loop_checkpoint = _system_methods.load_latest_open_loop_checkpoint
RuntimeStorageRepository.append_loop_checkpoint_step = _system_methods.append_loop_checkpoint_step
RuntimeStorageRepository.list_loop_checkpoint_steps = _system_methods.list_loop_checkpoint_steps
RuntimeStorageRepository.list_loop_checkpoints = _system_methods.list_loop_checkpoints

RuntimeStorageRepository.upsert_auth_profile = _scope_methods.upsert_auth_profile
RuntimeStorageRepository.load_auth_profile = _scope_methods.load_auth_profile
RuntimeStorageRepository.list_auth_profiles = _scope_methods.list_auth_profiles
RuntimeStorageRepository.select_auth_profile = _scope_methods.select_auth_profile
RuntimeStorageRepository.upsert_auth_secret_value = _scope_methods.upsert_auth_secret_value
RuntimeStorageRepository.load_auth_secret_value = _scope_methods.load_auth_secret_value
RuntimeStorageRepository.has_auth_secret_value = _scope_methods.has_auth_secret_value
RuntimeStorageRepository.delete_auth_secret_value = _scope_methods.delete_auth_secret_value
RuntimeStorageRepository.upsert_semantic_index_entry = _scope_methods.upsert_semantic_index_entry
RuntimeStorageRepository.load_semantic_index_entry = _scope_methods.load_semantic_index_entry
RuntimeStorageRepository.list_semantic_index_entries = _scope_methods.list_semantic_index_entries
RuntimeStorageRepository.delete_semantic_index_entries = _scope_methods.delete_semantic_index_entries
RuntimeStorageRepository.upsert_provider_auth_state = _provider_auth_methods.upsert_provider_auth_state
RuntimeStorageRepository.load_provider_auth_state = _provider_auth_methods.load_provider_auth_state
RuntimeStorageRepository.list_provider_auth_states = _provider_auth_methods.list_provider_auth_states

# Curiosity (v5): Fact / OpenQuestion / Diary tables.
RuntimeStorageRepository.upsert_personal_model_fact = (
    _curiosity_methods.upsert_personal_model_fact
)
RuntimeStorageRepository.touch_fact_access = (
    _curiosity_methods.touch_fact_access
)
RuntimeStorageRepository.list_personal_model_facts = (
    _curiosity_methods.list_personal_model_facts
)
RuntimeStorageRepository.upsert_open_question = _curiosity_methods.upsert_open_question
RuntimeStorageRepository.list_open_questions = _curiosity_methods.list_open_questions
RuntimeStorageRepository.mark_open_question = _curiosity_methods.mark_open_question
RuntimeStorageRepository.delete_open_question = _curiosity_methods.delete_open_question
RuntimeStorageRepository.upsert_diary_entry = _curiosity_methods.upsert_diary_entry
RuntimeStorageRepository.load_diary_entry = _curiosity_methods.load_diary_entry
RuntimeStorageRepository.delete_diary_entry = _curiosity_methods.delete_diary_entry
RuntimeStorageRepository.list_diary_entries = _curiosity_methods.list_diary_entries

__all__ = [
    "RuntimeStorageRepository",
    "StorageBootstrapState",
]
