"""Public inventory of memory package surfaces."""

MEMORY_SURFACES = (
    "MemoryCaptureRequest",
    "MemoryCaptureResult",
    "PersonalModelWriteRequest",
    "PersonalModelWriteResult",
    "ReflectionWindowResult",
    "StyleTraitSignalInput",
    "ReflectionProposalLifecycleResult",
    "MemoryLedgerEntry",
    "MemoryAppendResult",
    "MemoryRetrievalCandidate",
    "MemoryRetrievalResult",
    "MemoryConsolidationResult",
    "MemoryGovernanceDecision",
    "MemoryGovernanceEvent",
    "MemoryGovernancePolicy",
    "MemoryLedger",
    "MemoryStore",
    "MemoryExtractor",
    "DefaultMemoryExtractor",
    "DefaultMemoryConsolidator",
    "DefaultMemoryRetriever",
    "DefaultMemoryGovernance",
    "InMemoryMemoryLedger",
    "InMemoryMemoryStore",
    "SQLiteMemoryLedger",
    "SQLiteMemoryStore",
    "build_structured_turn_memory",
    "parse_structured_turn_memory",
    "MemoryRuntime",
)
