"""Shared runtime contracts for Elephant Agent.

This package is intentionally dependency-light and side-effect-free. It defines
the stable data shapes that the kernel, modules, and surfaces can share while
developing in parallel.
"""

from .inventory import CONTRACT_SURFACES
from .layers import Episode, Loop, PersonalModel, State, Step
from .personal_model import (
    ALLOWED_FACT_SOURCES,
    ALLOWED_FACT_STATUSES,
    ALLOWED_LEARNING_INTENSITIES,
    ALLOWED_LENSES,
    ALLOWED_QUESTION_SOURCES,
    ALLOWED_QUESTION_STATUSES,
    ALLOWED_SENSITIVITIES,
    DiaryEntry,
    Fact,
    OpenQuestion,
)
from .providers import (
    ActiveProviderSelection,
    GenerationProviderConfig,
)
from .support import SemanticIndexEntry
from .runtime import (
    LoopStep,
    ElephantIdentityRecord,
    ContextBundle,
    EmbeddingIndexInvalidation,
    EmbeddingIndexPolicy,
    EmbeddingIndexRebuildPlan,
    EvidenceCandidate,
    EvidenceRetrievalRequest,
    EvidenceRetrievalResult,
    EventEnvelope,
    ExperienceRecord,
    ExecutionResult,
    LearningJob,
    StateFocusCandidate,
    StateFocusCandidateScore,
    StateFocusReason,
    PlanDraft,
    PlanStep,
    PromptEnvelope,
    PromptMessage,
    ProcedureLibrary,
    ProcedureRecord,
    ProcedureStep,
    PersonalModelGrowthState,
    PersonalModelRuntimeState,
    RecallEvidence,
    RecallReason,
    RecallReasons,
    ResumePacket,
    EpisodeContinuityState,
    StepReplayRecord,
    StructuredTurnSlot,
)

__all__ = [
    "ActiveProviderSelection",
    "ALLOWED_FACT_SOURCES",
    "ALLOWED_FACT_STATUSES",
    "ALLOWED_LEARNING_INTENSITIES",
    "ALLOWED_LENSES",
    "ALLOWED_QUESTION_SOURCES",
    "ALLOWED_QUESTION_STATUSES",
    "ALLOWED_SENSITIVITIES",
    "CONTRACT_SURFACES",
    "ContextBundle",
    "DiaryEntry",
    "ElephantIdentityRecord",
    "EmbeddingIndexInvalidation",
    "EmbeddingIndexPolicy",
    "EmbeddingIndexRebuildPlan",
    "Episode",
    "EpisodeContinuityState",
    "EventEnvelope",
    "EvidenceCandidate",
    "EvidenceRetrievalRequest",
    "EvidenceRetrievalResult",
    "ExecutionResult",
    "ExperienceRecord",
    "Fact",
    "GenerationProviderConfig",
    "LearningJob",
    "Loop",
    "LoopStep",
    "OpenQuestion",
    "PersonalModel",
    "PersonalModelGrowthState",
    "PersonalModelRuntimeState",
    "RecallEvidence",
    "PlanDraft",
    "PlanStep",
    "ProcedureLibrary",
    "ProcedureRecord",
    "ProcedureStep",
    "PromptEnvelope",
    "PromptMessage",
    "RecallReason",
    "RecallReasons",
    "ResumePacket",
    "SemanticIndexEntry",
    "StepReplayRecord",
    "State",
    "StateFocusCandidate",
    "StateFocusCandidateScore",
    "StateFocusReason",
    "Step",
    "StructuredTurnSlot",
]
