"""Shared runtime contracts for Elephant Agent.

This package is intentionally dependency-light and side-effect-free. It defines
the stable data shapes that the kernel, modules, and surfaces can share while
developing in parallel.
"""

from .inventory import CONTRACT_SURFACES
from .layers import Episode, Loop, PersonalModel, State, Step
from .personal_model import (
    ALLOWED_FACT_SOURCES,
    ALLOWED_FACT_STATUSES,
    ALLOWED_LEARNING_INTENSITIES,
    ALLOWED_LENSES,
    ALLOWED_OBSERVATION_SOURCES,
    ALLOWED_OBSERVATION_STATUSES,
    ALLOWED_QUESTION_SOURCES,
    ALLOWED_QUESTION_STATUSES,
    ALLOWED_SENSITIVITIES,
    DiaryEntry,
    Fact,
    Observation,
    OpenQuestion,
)
from .providers import (
    ActiveProviderSelection,
    GenerationProviderConfig,
)
from .support import (
    Grounding,
    MemoryEntry,
    Record,
    ReflectionProposal,
    SemanticIndexEntry,
)
from .runtime import (
    LoopStep,
    ArtifactRecord,
    ElephantIdentityRecord,
    ContextBundle,
    EmbeddingIndexInvalidation,
    EmbeddingIndexPolicy,
    EmbeddingIndexRebuildPlan,
    EvidenceCandidate,
    EvidenceRecordBundle,
    EvidenceRetrievalRequest,
    EvidenceRetrievalResult,
    EventEnvelope,
    ExperienceRecord,
    ExecutionResult,
    LearningJob,
    StateFocusCandidate,
    StateFocusCandidateScore,
    StateFocusReason,
    MemoryRecord,
    PlanDraft,
    PlanStep,
    PromptEnvelope,
    PromptMessage,
    ProcedureLibrary,
    ProcedureRecord,
    ProcedureStep,
    PersonalModelRecordBundle,
    PersonalModelGrowthState,
    PersonalModelRuntimeState,
    RecallReason,
    RecallReasons,
    RelationshipMemoryRecord,
    ResumePacket,
    EpisodeContinuityState,
    StructuredTurnRecord,
    StructuredTurnSlot,
    UserCardRecord,
)

__all__ = [
    "ActiveProviderSelection",
    "ALLOWED_FACT_SOURCES",
    "ALLOWED_FACT_STATUSES",
    "ALLOWED_LEARNING_INTENSITIES",
    "ALLOWED_LENSES",
    "ALLOWED_OBSERVATION_SOURCES",
    "ALLOWED_OBSERVATION_STATUSES",
    "ALLOWED_QUESTION_SOURCES",
    "ALLOWED_QUESTION_STATUSES",
    "ALLOWED_SENSITIVITIES",
    "ArtifactRecord",
    "CONTRACT_SURFACES",
    "ContextBundle",
    "DiaryEntry",
    "ElephantIdentityRecord",
    "EmbeddingIndexInvalidation",
    "EmbeddingIndexPolicy",
    "EmbeddingIndexRebuildPlan",
    "Episode",
    "EpisodeContinuityState",
    "EventEnvelope",
    "EvidenceCandidate",
    "EvidenceRecordBundle",
    "EvidenceRetrievalRequest",
    "EvidenceRetrievalResult",
    "ExecutionResult",
    "ExperienceRecord",
    "Fact",
    "GenerationProviderConfig",
    "Grounding",
    "LearningJob",
    "Loop",
    "LoopStep",
    "MemoryEntry",
    "MemoryRecord",
    "Observation",
    "OpenQuestion",
    "PersonalModel",
    "PersonalModelGrowthState",
    "PersonalModelRecordBundle",
    "PersonalModelRuntimeState",
    "PlanDraft",
    "PlanStep",
    "ProcedureLibrary",
    "ProcedureRecord",
    "ProcedureStep",
    "PromptEnvelope",
    "PromptMessage",
    "RecallReason",
    "RecallReasons",
    "Record",
    "ReflectionProposal",
    "RelationshipMemoryRecord",
    "ResumePacket",
    "SemanticIndexEntry",
    "State",
    "StateFocusCandidate",
    "StateFocusCandidateScore",
    "StateFocusReason",
    "Step",
    "StructuredTurnRecord",
    "StructuredTurnSlot",
    "UserCardRecord",
]
