"""Executable tool capabilities for Elephant Agent."""

from .builtins import (
    builtin_tool_definitions,
    render_builtin_tool_reference_markdown,
    render_builtin_tool_summary_markdown,
    register_builtin_tools,
)
from .factory import build_secured_tool_runtime, build_tool_runtime
from .inventory import TOOL_SURFACES
from .mcp import custom_mcp_runtime_entries, mcp_runtime_tool_id, sync_custom_mcp_tools
from .adapters import RequesterScopedToolCapability
from .runtime import (
    ApprovalGateway,
    build_tool_fallback_prompt,
    CallableApprovalGateway,
    InMemoryToolExecutor,
    InMemoryToolRegistry,
    JsonToolLoader,
    SecurityApprovalGateway,
    ToolApprovalResult,
    ToolAvailability,
    ToolDefinition,
    ToolAudience,
    ToolExecutionBackend,
    ToolExecutionRecord,
    ToolHandler,
    ToolLifecycleEvent,
    ToolInvocation,
    ToolLoader,
    ToolManifest,
    ToolManifestLoadRecord,
    ToolObserver,
    ToolRuntimeContext,
    ToolRequester,
    ToolRegistry,
    ToolRuntime,
    ToolSideEffectMetadata,
)
from .surfaces import BrowserVisionAnalyzer, BuiltinToolDependencies, InMemorySessionTodoStore

__all__ = [
    "ApprovalGateway",
    "BrowserVisionAnalyzer",
    "CallableApprovalGateway",
    "build_tool_fallback_prompt",
    "BuiltinToolDependencies",
    "custom_mcp_runtime_entries",
    "InMemorySessionTodoStore",
    "InMemoryToolExecutor",
    "InMemoryToolRegistry",
    "mcp_runtime_tool_id",
    "JsonToolLoader",
    "SecurityApprovalGateway",
    "RequesterScopedToolCapability",
    "TOOL_SURFACES",
    "ToolApprovalResult",
    "ToolAudience",
    "ToolAvailability",
    "ToolDefinition",
    "ToolExecutionBackend",
    "ToolExecutionRecord",
    "ToolHandler",
    "ToolLifecycleEvent",
    "ToolInvocation",
    "ToolLoader",
    "ToolManifest",
    "ToolManifestLoadRecord",
    "ToolObserver",
    "ToolRuntimeContext",
    "ToolRequester",
    "ToolRegistry",
    "ToolRuntime",
    "ToolSideEffectMetadata",
    "builtin_tool_definitions",
    "build_secured_tool_runtime",
    "build_tool_runtime",
    "render_builtin_tool_reference_markdown",
    "render_builtin_tool_summary_markdown",
    "register_builtin_tools",
    "sync_custom_mcp_tools",
]
